// Toutes les 200 commandes du bot IB-HEX-BOT

export const commands = [
    // MENU GÉNÉRAL (6 commandes)
    { cmd: 'menu', category: 'général', description: 'Afficher le menu principal' },
    { cmd: 'alive', category: 'général', description: 'État du bot' },
    { cmd: 'dev', category: 'général', description: 'Info développeur' },
    { cmd: 'allvar', category: 'général', description: 'Toutes les variables' },
    { cmd: 'ping', category: 'général', description: 'Vitesse du bot' },
    { cmd: 'owner', category: 'général', description: 'Propriétaire' },

    // OWNER (9 commandes)
    { cmd: 'join', category: 'owner', description: 'Rejoindre un groupe' },
    { cmd: 'leave', category: 'owner', description: 'Quitter un groupe' },
    { cmd: 'antidelete', category: 'owner', description: 'Anti-suppression' },
    { cmd: 'upload', category: 'owner', description: 'Téléverser' },
    { cmd: 'vv', category: 'owner', description: 'Vue unique' },
    { cmd: 'allcmds', category: 'owner', description: 'Toutes les commandes' },
    { cmd: 'delete', category: 'owner', description: 'Supprimer message' },
    { cmd: '🥷', category: 'owner', description: 'Vue unique privé' },
    { cmd: 'repo', category: 'owner', description: 'Dépôt GitHub' },

    // IA (6 commandes)
    { cmd: 'ai', category: 'ia', description: 'Intelligence artificielle' },
    { cmd: 'bug', category: 'ia', description: 'Signaler un bug' },
    { cmd: 'bot', category: 'ia', description: 'Informations bot' },
    { cmd: 'gemini', category: 'ia', description: 'IA Gemini' },
    { cmd: 'chatbot', category: 'ia', description: 'Discussion IA' },
    { cmd: 'gpt', category: 'ia', description: 'ChatGPT' },

    // CONVERTISSEUR (9 commandes)
    { cmd: 'attp', category: 'convertisseur', description: 'Texte en sticker' },
    { cmd: 'toimage', category: 'convertisseur', description: 'Convertir en image' },
    { cmd: 'gimage', category: 'convertisseur', description: 'Image Google' },
    { cmd: 'mp3', category: 'convertisseur', description: 'Convertir en MP3' },
    { cmd: 'ss', category: 'convertisseur', description: "Capture d'écran" },
    { cmd: 'fancy', category: 'convertisseur', description: 'Texte stylé' },
    { cmd: 'url', category: 'convertisseur', description: 'Lien' },
    { cmd: 'sticker', category: 'convertisseur', description: 'Créer sticker' },
    { cmd: 'take', category: 'convertisseur', description: 'Récupérer média' },

    // RECHERCHE (10 commandes)
    { cmd: 'google', category: 'recherche', description: 'Recherche Google' },
    { cmd: 'play', category: 'recherche', description: 'Play Store' },
    { cmd: 'video', category: 'recherche', description: 'Recherche vidéo' },
    { cmd: 'song', category: 'recherche', description: 'Musique' },
    { cmd: 'mediafire', category: 'recherche', description: 'MediaFire' },
    { cmd: 'facebook', category: 'recherche', description: 'Facebook' },
    { cmd: 'instagram', category: 'recherche', description: 'Instagram' },
    { cmd: 'tiktok', category: 'recherche', description: 'TikTok' },
    { cmd: 'lyrics', category: 'recherche', description: 'Paroles' },
    { cmd: 'image', category: 'recherche', description: 'Images' },

    // DIVERTISSEMENT (9 commandes)
    { cmd: 'getpp', category: 'divertissement', description: 'Photo de profil' },
    { cmd: 'goodnight', category: 'divertissement', description: 'Bonne nuit' },
    { cmd: 'wcg', category: 'divertissement', description: 'Classement' },
    { cmd: 'quizz', category: 'divertissement', description: 'Quiz' },
    { cmd: 'anime', category: 'divertissement', description: 'Anime' },
    { cmd: 'profile', category: 'divertissement', description: 'Profil' },
    { cmd: 'couple', category: 'divertissement', description: 'Couple' },
    { cmd: 'poll', category: 'divertissement', description: 'Sondage' },
    { cmd: 'emojimix', category: 'divertissement', description: "Mélange d'emojis" },

    // GROUPES (15 commandes)
    { cmd: 'kickall', category: 'groupe', description: 'Exclure tous' },
    { cmd: 'tagadmin', category: 'groupe', description: 'Mention admins' },
    { cmd: 'acceptall', category: 'groupe', description: 'Accepter tous' },
    { cmd: 'tagall', category: 'groupe', description: 'Mentionner tous' },
    { cmd: 'getall', category: 'groupe', description: 'Récupérer membres' },
    { cmd: 'groupclose', category: 'groupe', description: 'Fermer groupe' },
    { cmd: 'groupopen', category: 'groupe', description: 'Ouvrir groupe' },
    { cmd: 'add', category: 'groupe', description: 'Ajouter membre' },
    { cmd: 'vcf', category: 'groupe', description: 'Contacts VCF' },
    { cmd: 'linkgc', category: 'groupe', description: 'Lien du groupe' },
    { cmd: 'antilink', category: 'groupe', description: 'Anti-lien' },
    { cmd: 'antisticker', category: 'groupe', description: 'Anti-sticker' },
    { cmd: 'antigm', category: 'groupe', description: 'Anti-mention' },
    { cmd: 'create', category: 'groupe', description: 'Créer groupe' },
    { cmd: 'groupinfo', category: 'groupe', description: 'Infos groupe' },

    // RÉACTIONS (10 commandes)
    { cmd: 'yeet', category: 'réaction', description: 'Jeter' },
    { cmd: 'slap', category: 'réaction', description: 'Gifler' },
    { cmd: 'nom', category: 'réaction', description: 'Manger' },
    { cmd: 'poke', category: 'réaction', description: 'Toucher' },
    { cmd: 'wave', category: 'réaction', description: 'Saluer' },
    { cmd: 'smile', category: 'réaction', description: 'Sourire' },
    { cmd: 'dance', category: 'réaction', description: 'Danser' },
    { cmd: 'smug', category: 'réaction', description: 'Sourire narquois' },
    { cmd: 'cringe', category: 'réaction', description: 'Malaise' },
    { cmd: 'happy', category: 'réaction', description: 'Heureux' },

    // MÉDIAS (15 commandes)
    { cmd: 'ytmp3', category: 'média', description: 'YouTube MP3' },
    { cmd: 'ytmp4', category: 'média', description: 'YouTube MP4' },
    { cmd: 'twitter', category: 'média', description: 'Twitter downloader' },
    { cmd: 'pinterest', category: 'média', description: 'Pinterest' },
    { cmd: 'soundcloud', category: 'média', description: 'SoundCloud' },
    { cmd: 'spotify', category: 'média', description: 'Spotify' },
    { cmd: 'apk', category: 'média', description: 'Télécharger APK' },
    { cmd: 'wallpaper', category: 'média', description: 'Fond écran' },
    { cmd: 'ringtone', category: 'média', description: 'Sonnerie' },
    { cmd: 'movie', category: 'média', description: 'Info film' },
    { cmd: 'weather', category: 'média', description: 'Météo' },
    { cmd: 'news', category: 'média', description: 'Actualités' },
    { cmd: 'wiki', category: 'média', description: 'Wikipedia' },
    { cmd: 'translate', category: 'média', description: 'Traduire' },
    { cmd: 'define', category: 'média', description: 'Définition' },

    // UTILITAIRES (20 commandes)
    { cmd: 'calc', category: 'utilitaire', description: 'Calculatrice' },
    { cmd: 'qrcode', category: 'utilitaire', description: 'Générer QR code' },
    { cmd: 'readqr', category: 'utilitaire', description: 'Lire QR code' },
    { cmd: 'shorturl', category: 'utilitaire', description: 'Raccourcir URL' },
    { cmd: 'base64', category: 'utilitaire', description: 'Encoder Base64' },
    { cmd: 'readmore', category: 'utilitaire', description: 'Lire plus' },
    { cmd: 'textmaker', category: 'utilitaire', description: 'Créer texte' },
    { cmd: 'tourl', category: 'utilitaire', description: 'Média vers URL' },
    { cmd: 'reminder', category: 'utilitaire', description: 'Rappel' },
    { cmd: 'timer', category: 'utilitaire', description: 'Minuteur' },
    { cmd: 'encrypt', category: 'utilitaire', description: 'Chiffrer' },
    { cmd: 'decrypt', category: 'utilitaire', description: 'Déchiffrer' },
    { cmd: 'hash', category: 'utilitaire', description: 'Hash MD5/SHA' },
    { cmd: 'binary', category: 'utilitaire', description: 'Binaire' },
    { cmd: 'hex', category: 'utilitaire', description: 'Hexadécimal' },
    { cmd: 'reverse', category: 'utilitaire', description: 'Inverser texte' },
    { cmd: 'length', category: 'utilitaire', description: 'Longueur texte' },
    { cmd: 'uppercase', category: 'utilitaire', description: 'Majuscules' },
    { cmd: 'lowercase', category: 'utilitaire', description: 'Minuscules' },
    { cmd: 'random', category: 'utilitaire', description: 'Nombre aléatoire' },

    // JEUX (15 commandes)
    { cmd: 'truth', category: 'jeu', description: 'Vérité' },
    { cmd: 'dare', category: 'jeu', description: 'Défi' },
    { cmd: 'ship', category: 'jeu', description: 'Compatibilité' },
    { cmd: 'dice', category: 'jeu', description: 'Lancer dé' },
    { cmd: 'coin', category: 'jeu', description: 'Pile ou face' },
    { cmd: 'rate', category: 'jeu', description: 'Noter' },
    { cmd: '8ball', category: 'jeu', description: 'Boule magique' },
    { cmd: 'rps', category: 'jeu', description: 'Pierre papier ciseaux' },
    { cmd: 'slot', category: 'jeu', description: 'Machine à sous' },
    { cmd: 'trivia', category: 'jeu', description: 'Culture générale' },
    { cmd: 'riddle', category: 'jeu', description: 'Énigme' },
    { cmd: 'joke', category: 'jeu', description: 'Blague' },
    { cmd: 'meme', category: 'jeu', description: 'Meme aléatoire' },
    { cmd: 'roast', category: 'jeu', description: 'Clash' },
    { cmd: 'compliment', category: 'jeu', description: 'Compliment' },

    // IMAGES IA (15 commandes)
    { cmd: 'imagine', category: 'image-ia', description: 'Générer image IA' },
    { cmd: 'anime-art', category: 'image-ia', description: 'Art anime' },
    { cmd: 'portrait', category: 'image-ia', description: 'Portrait IA' },
    { cmd: 'landscape', category: 'image-ia', description: 'Paysage IA' },
    { cmd: 'fantasy', category: 'image-ia', description: 'Fantasy art' },
    { cmd: 'cyberpunk', category: 'image-ia', description: 'Style cyberpunk' },
    { cmd: 'cartoon', category: 'image-ia', description: 'Cartoon' },
    { cmd: 'realistic', category: 'image-ia', description: 'Réaliste' },
    { cmd: 'sketch', category: 'image-ia', description: 'Croquis' },
    { cmd: 'watercolor', category: 'image-ia', description: 'Aquarelle' },
    { cmd: 'oilpaint', category: 'image-ia', description: 'Peinture huile' },
    { cmd: 'pixel', category: 'image-ia', description: 'Pixel art' },
    { cmd: '3d', category: 'image-ia', description: 'Rendu 3D' },
    { cmd: 'logo', category: 'image-ia', description: 'Créer logo' },
    { cmd: 'poster', category: 'image-ia', description: 'Créer poster' },

    // ADMIN GROUPE (12 commandes)
    { cmd: 'promote', category: 'admin', description: 'Promouvoir admin' },
    { cmd: 'demote', category: 'admin', description: 'Rétrograder' },
    { cmd: 'kick', category: 'admin', description: 'Exclure membre' },
    { cmd: 'warn', category: 'admin', description: 'Avertir' },
    { cmd: 'resetwarn', category: 'admin', description: 'Reset avertissements' },
    { cmd: 'mute', category: 'admin', description: 'Mute membre' },
    { cmd: 'unmute', category: 'admin', description: 'Unmute membre' },
    { cmd: 'ban', category: 'admin', description: 'Bannir' },
    { cmd: 'unban', category: 'admin', description: 'Débannir' },
    { cmd: 'setname', category: 'admin', description: 'Nom du groupe' },
    { cmd: 'setdesc', category: 'admin', description: 'Description groupe' },
    { cmd: 'setpp', category: 'admin', description: 'Photo de groupe' },

    // RELIGION (10 commandes)
    { cmd: 'quran', category: 'religion', description: 'Verset Coran' },
    { cmd: 'hadith', category: 'religion', description: 'Hadith' },
    { cmd: 'prayer', category: 'religion', description: 'Heures prière' },
    { cmd: 'islamic', category: 'religion', description: 'Info islamique' },
    { cmd: 'dua', category: 'religion', description: 'Invocation' },
    { cmd: 'bible', category: 'religion', description: 'Verset Bible' },
    { cmd: 'allah', category: 'religion', description: 'Noms Allah' },
    { cmd: 'asma', category: 'religion', description: 'Asma ul Husna' },
    { cmd: 'hijri', category: 'religion', description: 'Date hijri' },
    { cmd: 'tafsir', category: 'religion', description: 'Tafsir' },

    // ÉCONOMIE (10 commandes)
    { cmd: 'balance', category: 'économie', description: 'Solde' },
    { cmd: 'daily', category: 'économie', description: 'Bonus quotidien' },
    { cmd: 'work', category: 'économie', description: 'Travailler' },
    { cmd: 'transfer', category: 'économie', description: 'Transférer' },
    { cmd: 'deposit', category: 'économie', description: 'Déposer' },
    { cmd: 'withdraw', category: 'économie', description: 'Retirer' },
    { cmd: 'rob', category: 'économie', description: 'Voler' },
    { cmd: 'shop', category: 'économie', description: 'Boutique' },
    { cmd: 'buy', category: 'économie', description: 'Acheter' },
    { cmd: 'leaderboard', category: 'économie', description: 'Classement' },

    // INFOS (10 commandes)
    { cmd: 'covid', category: 'info', description: 'Stats COVID' },
    { cmd: 'crypto', category: 'info', description: 'Crypto monnaies' },
    { cmd: 'stock', category: 'info', description: 'Actions bourse' },
    { cmd: 'country', category: 'info', description: 'Info pays' },
    { cmd: 'flag', category: 'info', description: 'Drapeau pays' },
    { cmd: 'time', category: 'info', description: 'Heure mondiale' },
    { cmd: 'npm', category: 'info', description: 'Package NPM' },
    { cmd: 'github', category: 'info', description: 'Profil GitHub' },
    { cmd: 'ip', category: 'info', description: 'Info IP' },
    { cmd: 'phone', category: 'info', description: 'Info numéro' },

    // MODÉRATION (9 commandes)
    { cmd: 'autoblock', category: 'modération', description: 'Auto-blocage' },
    { cmd: 'autokick', category: 'modération', description: 'Auto-exclusion' },
    { cmd: 'antibot', category: 'modération', description: 'Anti-bot' },
    { cmd: 'antiviewonce', category: 'modération', description: 'Anti-vue unique' },
    { cmd: 'antispam', category: 'modération', description: 'Anti-spam' },
    { cmd: 'antiword', category: 'modération', description: 'Anti-gros mots' },
    { cmd: 'filter', category: 'modération', description: 'Filtrer mots' },
    { cmd: 'welcome', category: 'modération', description: 'Message bienvenue' },
    { cmd: 'goodbye', category: 'modération', description: 'Message départ' },

    // AUDIO (10 commandes)
    { cmd: 'bass', category: 'audio', description: 'Booster basses' },
    { cmd: 'nightcore', category: 'audio', description: 'Effet nightcore' },
    { cmd: 'slow', category: 'audio', description: 'Ralentir audio' },
    { cmd: 'fast', category: 'audio', description: 'Accélérer audio' },
    { cmd: 'reverse-audio', category: 'audio', description: 'Inverser audio' },
    { cmd: 'robot', category: 'audio', description: 'Voix robot' },
    { cmd: 'echo', category: 'audio', description: 'Effet écho' },
    { cmd: 'earrape', category: 'audio', description: 'Earrape' },
    { cmd: 'volume', category: 'audio', description: 'Changer volume' },
    { cmd: 'pitch', category: 'audio', description: 'Changer pitch' }
];

export default commands;
